# Generated by Django 3.1.13 on 2022-01-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topping',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name=''),
            preserve_default=False,
        ),
    ]
