# Generated by Django 3.1.13 on 2022-01-10 05:53

from django.db import migrations
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0002_auto_20220109_0534"),
    ]

    def create_questions_answers(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        Question = apps.get_model("playground", "Question")
        Question.objects.create(question_text="Q1", pub_date=date.today())

    operations = [
        migrations.RunPython(create_questions_answers),
    ]
